<a href="https://colab.research.google.com/github/erdijova/Practical-Linear-Algebra-for-Data-Science/blob/main/10_chapter10_Row_Reduction_and_LU_Decomposition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Row Reduction and LU Decomposition**

Systems of Equations
To understand LU decomposition and its applications, you need to understand row
reduction and Gaussian elimination. And to understand those topics, you need to
understand how to manipulate equations, convert them into a matrix equation, and
solve that matrix equation using row reduction.

Converting systems of equations into a matrix-vector equation is used to solve sys‐
tems of equations, and it’s used to set up the formula for the general linear model in
statistics. Fortunately, translating equations into matrices is conceptually simple, and
involves two steps.

**Working with Matrix Equations**

You can manipulate matrix equations just like normal equations, including adding,
multiplying, transposing, etc., as long as the manipulations are valid (e.g., matrix
sizes match for addition) and all manipulations affect both sides of the equation.

In [5]:
A = np.random.randn(4,4)
B = np.random.randn(4,4)
# solve for X
X1 = np.linalg.inv(A) @ B
X2 = B @ np.linalg.inv(A)
# residual (should be zeros matrix)
res1 = A@X1 - B
res2 = A@X2 - B

**Row Reduction**

Row reduction is a topic that gets a lot of attention in traditional linear algebra,
because it is the time-honored way to solve systems of equations by hand. I seriously
doubt you’ll solve any systems of equations by hand in your career as a data scientist.
But row reduction is useful to know about, and it leads directly to LU decomposition,
which actually is used in applied linear algebra. So let’s begin.

Row reduction means iteratively applying two operations—scalar multiplication and
addition—to rows of a matrix. Row reduction relies on the same principle as adding
equations to other equations within a system.

**Gaussian Elimination**

At this point in the book, you know how to solve matrix equations using the matrix
inverse. What if I told you that you could solve a matrix equation without inverting
any matrices?3

This technique is called Gaussian elimination. Despite its name, the algorithm was
actually developed by Chinese mathematicians nearly two thousand years before
Gauss and then rediscovered by Newton hundreds of years before Gauss. But Gauss
made important contributions to the method, including the techniques that modern
computers implement.

**Gauss-Jordan Elimination**

Let’s keep row reducing our example matrix with the goal of turning all the pivots
—the leftmost nonzero numbers in each row—into 1s. Once you have the echelon
matrix, you simply divide each row by its pivot. In this example, the first row already
has a 1 in the leftmost position

Gauss-Jordan elimination was how people solved systems of equations by hand for
over a century before computers came along to help us with the number crunching.
In fact, computers still implement this exact same method, with only a few small
modifications to ensure numerical stability.

In [6]:
import sympy as sym
# the matrix converted to sympy
M = np.array([ [1,1,4],[-1/2,1,2] ])
symMat = sym.Matrix(M)
# RREF
symMat.rref()[0]

Matrix([
[1, 0, 1.33333333333333],
[0, 1, 2.66666666666667]])

**Matrix Inverse via Gauss-Jordan Elimination**

The key insight from Gauss-Jordan elimination is that row reduction produces a
sequence of row manipulations that solves a set of equations. Those row manipula‐
tions are linear transformations.

Curiously, the description of Gauss-Jordan elimination is consistent with the descrip‐
tion of the matrix inverse: a linear transformation that solves a set of equations. But
wait, what “system of equations” does the matrix inverse solve? A fresh perspective on
the matrix inverse will provide some new insights.

LU Decomposition

The “LU” in LU decomposition stands for “lower upper,” as in lower-triangular, upper-
triangular.

In [7]:
import scipy.linalg # LU in scipy library
A = np.array([ [2,2,4], [1,0,3], [2,1,2] ])
_,L,U = scipy.linalg.lu(A)
# print them out
print('L: '), print(L)
print('U: '), print(U)

L: 
[[1.  0.  0. ]
 [0.5 1.  0. ]
 [1.  1.  1. ]]
U: 
[[ 2.  2.  4.]
 [ 0. -1.  1.]
 [ 0.  0. -3.]]


(None, None)

Where do these two matrices come from? In fact, you already know the answer:
row reduction can be expressed as L

−1A = U, where L

−1 contains the set of row
manipulations that transforms the dense A into upper-triangular (echelon) U.

**Row Swaps via Permutation Matrices**

Remarkably, permutation matrices are orthogonal, and so P
−1
= P
T
. Briefly, the
reason is that all elements of a permutation matrix are either 0 or 1, and because
rows are swapped only once, each column has exactly one nonzero element (indeed,
all permutation matrices are identity matrices with row swaps). Therefore, the dot
product of any two columns is 0 while the dot product of a column with itself is 1,
meaning P
T
P = I.